name: Generate New Post

on:
  repository_dispatch:
    types: [new_blog_post]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Write payload to file
        run: |
          echo '${{ toJSON(github.event.client_payload) }}' > payload.json

      - name: Generate postX.html
        run: node generate-post.js

      - name: Commit post file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add post*.html
          git commit -m "New post: ${{ github.event.client_payload.title }}" || echo "No changes"
          git push
