name: Generate Post from Issue

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install jsdom

      - name: Generate post from issue
        run: |
          node generate-from-issue.js "${{ github.event.issue.title }}" "${{ github.event.issue.body }}"

      - name: Generate updated index
        run: node generate-index.js

      - name: Commit post and updated index
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add post*.html index.html
          git commit -m "Auto-generate post and index from issue" || echo "No changes"
          git push
