name: Generate Post from Issue

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install js-yaml

      - name: Save issue payload
        run: |
          echo '${{ toJSON(github.event.issue) }}' > issue.json

      - name: Generate post from issue
        run: node generate-from-issue.js

      - name: Commit post
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add post*.html
          git commit -m "Generate post from issue #${{ github.event.issue.number }}" || echo "No changes"
          git push

      - name: Run generate-index.js
        run: node generate-index.js

      - name: Commit updated index
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update index.html after post creation" || echo "No changes"
          git push
