name: Generate index.html

on:
  push:
    paths:
      - 'post*.html'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: node generate-index.js

      - name: Commit and push index.html
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Auto update index.html"
          git push
