name: Issue to Blog Post

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Generate post HTML
      run: |
        mkdir -p posts
        TITLE=$(echo "${{ github.event.issue.body }}" | grep '^title:' | sed 's/title: //')
        DATE=$(echo "${{ github.event.issue.body }}" | grep '^date:' | sed 's/date: //')
        BODY=$(echo "${{ github.event.issue.body }}" | awk '/^---$/,/^---$/{next} 1')
        NUM=$(ls posts | grep -o 'post[0-9]*\.html' | sed 's/post\([0-9]*\)\.html/\1/' | sort -n | tail -1)
        NEXT=$((NUM + 1))
        FILENAME=post${NEXT}.html

        echo "<!DOCTYPE html>
<html lang=\"ja\">
<head>
  <meta charset=\"UTF-8\">
  <title>${TITLE}</title>
  <link href=\"https://fonts.googleapis.com/css2?family=DotGothic16&family=Press+Start+2P&family=Share+Tech+Mono&display=swap\" rel=\"stylesheet\">
  <link rel=\"stylesheet\" href=\"style.css\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
</head>
<body>
  <div class=\"container\">
    <article>
      <h2 class=\"title\"><a class=\"neon\" href=\"#\">＞＞ ${TITLE}</a></h2>
      <p class=\"meta\">${DATE}</p>
      <div class=\"article-body\">${BODY//'\n'/<br>}</div>
      <p class=\"neon\"><a href=\"index.html\">←START</a></p>
    </article>
  </div>
</body>
</html>" > posts/$FILENAME

    - name: Commit and push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add posts/
        git commit -m "Add: ${FILENAME}"
        git push
