name: Generate blog post from Issue

on:
  issues:
    types: [opened]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract and create post HTML
        id: build
        run: |
          mkdir -p posts
          TITLE="${{ github.event.issue.title }}"
          BODY="${{ github.event.issue.body }}"
          DATE=$(echo "$BODY" | sed -n 's/^date: //p')
          CONTENT=$(echo "$BODY" | sed -n '/^---$/,/^---$/!p' | sed '1,2d')
          FILENAME="post$(date +%s).html"

          cat <<EOF > posts/$FILENAME
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>$TITLE</title>
  <link rel="stylesheet" href="style.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <div class="container">
    <article>
      <h2 class="title"><a class="neon" href="#">＞＞ $TITLE</a></h2>
      <p class="meta">$DATE</p>
      <div class="article-body">${CONTENT//$'\n'/<br>}</div>
      <p class="neon"><a href="index.html">←START</a></p>
    </article>
  </div>
</body>
</html>
EOF

          echo "filename=$FILENAME" >> $GITHUB_OUTPUT

      - name: Commit new post
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add posts/*.html
          git commit -m "Add blog post"
          git push

      - name: Re-generate index
        run: |
          echo "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Index</title><link rel='stylesheet' href='style.css'></head><body><h1>記事一覧</h1><ul>" > index.html
          for f in $(ls posts/*.html | sort -r); do
            title=$(grep -oP '(?<=<title>).*?(?=</title>)' "$f")
            echo "<li><a href=\"$f\">$title</a></li>" >> index.html
          done
          echo "</ul></body></html>" >> index.html

          git add index.html
          git commit -m "Update index"
          git push
