name: Generate post from issue

on:
  issues:
    types: [opened]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create postx.html from issue
        run: |
          echo "${{ github.event.issue.body }}" > issue.md
          TITLE=$(grep '^title:' issue.md | sed 's/^title: //')
          DATE=$(grep '^date:' issue.md | sed 's/^date: //')
          CONTENT=$(awk 'NR>3' issue.md)

          FILENAME="post${{ github.event.issue.number }}.html"
          echo "✅ Creating $FILENAME"

          cat > $FILENAME <<EOF
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>$TITLE</title>
  <link rel="stylesheet" href="style.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <div class="container">
    <article>
      <h2 class="title"><a class="neon" href="#">＞＞ $TITLE</a></h2>
      <p class="meta">$DATE</p>
      <div class="article-body">
        ${CONTENT//$'\n'/<br>}
      </div>
      <p class="neon"><a href="index.html">←START</a></p>
    </article>
  </div>
</body>
</html>
EOF

      - name: Commit post
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add post*.html
          git commit -m "投稿追加: $FILENAME"
          git push
