name: Generate post from issue

on:
  issues:
    types: [opened]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate HTML file
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          
          POST_TITLE=$(echo "$ISSUE_BODY" | sed -n 's/^title: //p')
          POST_DATE=$(echo "$ISSUE_BODY" | sed -n 's/^date: //p')
          POST_CONTENT=$(echo "$ISSUE_BODY" | sed -n '/^---$/,/^---$/!p' | sed '1,2d')

          FILENAME="post$(date +%s).html"

          cat <<EOF > $FILENAME
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>$POST_TITLE</title>
  <link rel="stylesheet" href="style.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <div class="container">
    <article>
      <h2 class="title"><a class="neon" href="#">＞＞ $POST_TITLE</a></h2>
      <p class="meta">$POST_DATE</p>
      <div class="article-body">${POST_CONTENT//$'\n'/<br>}</div>
      <p class="neon"><a href="index.html">←START</a></p>
    </article>
  </div>
</body>
</html>
EOF

          echo "✅ Created $FILENAME"

      - name: Commit post
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add post*.html
          git commit -m "Add blog post from issue"
          git push
